fastlane_version "1.109.0"

default_platform :android

platform :android do
  desc "Submit new Android build of Yemen Portal to Fabric Beta"
  lane :beta do
    gradle(
        task: "assemble",
        build_type: "Release",
        project_dir: "android/"
      )

    crashlytics(
      api_token: ENV["FABRIC_API_TOKEN"],
      build_secret: ENV["FABRIC_BUILD_SECRET"]
    )
  end
end

platform :ios do
  desc "Submit new iOS build of Yemen Portal to Fabric Beta"
  lane :beta do
    # Matching certificates
    match(
      type: "adhoc",
      readonly: true
    )

    # Building an app
    gym(
      scheme: "yemenportalmobile",
      configuration: "Ad Hoc",
      sdk: "iphoneos10.3",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      export_method: "ad-hoc",
      project: "ios/yemenportalmobile.xcodeproj"
    )

    # Pushing to Fabric Beta
    crashlytics(
      api_token: ENV["FABRIC_API_TOKEN"],
      build_secret: ENV["FABRIC_BUILD_SECRET"],
      crashlytics_path: "ios/Pods/Crashlytics"
    )
  end
end
